server {  
    listen 80 default_server;  
    #listen [::]:80 default_server;  
    server_name _;  # 匹配所有未显式指定的主机名/IP  
  
    return 444;  # 或 return 403; 或重定向  
}  
server {  
    listen 443 ssl default_server;  
    #listen [::]:443 ssl default_server;  
    server_name _;  
    ssl_certificate     /usr/local/nginx/conf/ssl/fake.crt;  
    ssl_certificate_key /usr/local/nginx/conf/ssl/fake.key;  
    return 444;  
}
